apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      index index.php index.html;
      root /var/www/html;

      location /healthz {
        set $do_log 0;
        try_files $uri $uri/ /index.php?$args;
      }

      location / {
        set $do_log 1;
        try_files $uri $uri/ /index.php?$args;
      }

      location ~ \.php$ {
        if ($do_log = 0) {
          access_log off;
        }
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
    }
